### ISSUE TITLE
Graph shows timestamps

### ISSUE THREAD

**Issue by ArmandasRokas** [ArmandasRokas/beeware#7]
It should be fixed to show dates not timestamp. Some solutions: https://github.com/PhilJay/MPAndroidChart/issues/789

**Comment by ErlendTyrmi** [comment]
Det kigger jeg på. Er det i aflevering 2-repo

**Comment by ArmandasRokas** [comment]
Det er fint :) Men husk at aflevering 2 vil blive slettet og kommer ikke til at blive merget til master. Så du kan vente indtil jeg får styr på data parsing på masteren.
